### ISSUE TITLE
Mongo container logs repeatedly show `Received interrupt request for unknown op`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#221]
With the following `entrypoint` in the `docker-compose.yml` file:

```yaml
  mongo:
    image: mongo:6.0.4
    restart: unless-stopped
    ports:
      - "27017:27017"
    # Map a persistent volume to `/data/db` within the container.
    volumes:
      - ${MONGO_DATA_DIR_ON_HOST:-/media/volume/nmdc-edge-web-app-mongo-data}:/data/db
    entrypoint: ["mongod", "--config", "/data/db/mongod.conf", "--setParameter", "logComponentVerbosity={query: {verbosity: 2}}"]
```

Mongo container logs repeatedly show "Received interrupt request for unknown op":

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/08340af7-cfe2-432a-8d70-5ee1053e313f)

Related forum post (unresolved): https://www.mongodb.com/community/forums/t/received-interrupt-request-for-unknown-op/128531

CC: @mflynn-lanl
